### ISSUE TITLE
[bug report] Feed integration broken in Firefox 60

### ISSUE THREAD

**Issue by n8v8R** [brief-rss/brief#343]
W10Pro x64 1709 b16299.125 / Firefox 59.0b13 x64

Has Brief yet been tested with the upcoming FF59? The experience this end is that Brief is not discovering feeds in FF59 and is not showing as feed handler/reader

![brief in ff59](https://user-images.githubusercontent.com/13611490/36852125-4753fd22-1d6b-11e8-96ec-a70a6207ee8f.PNG)

**Comment by tanriol** [comment]
Works for me on Firefox Nightly / Linux. What's your Brief version? Does the Brief page action show up?

**Comment by n8v8R** [comment]
Brief 2.5.5

Brief page action = Subscribe icon in the browser address bar? That shows in FF58 but not anymore in FF59. 

And like in this [example](https://cloudlinux.com/component/easyblog/?format=feed&type=rss&Itemid=292) there is no Brief listed as feed handler in FF59 (as shown in the image above), whilst it does so in FF58.

in FF59 disabled Fist Party Isolation and Resist Fingerprinting but that did not change the outcome. Suppose neither should have an impact on Brief anyway.

**Comment by franklinyu** [comment]
Works for me in Firefox 59.0, Windows 10.

**Comment by tanriol** [comment]
@n8v8R Haven't been able to reproduce it yet. Does it work for you in a separate Firefox profile?

**Comment by n8v8R** [comment]
thanks for looking into it and the feedback. No issues now with 59.0.2 (64-bit) on W10 1709 b16229.309

**Comment by franklinyu** [comment]
I met the same situation today. The Brief option disappeared on my Firefox 60.0b16 (beta) on Windows 10; I tested on another machine with Firefox 59.0.2 (stable) on Windows 8.1 and it worked great. So I guess something on Firefox 60 breaks it?

In addition, on Firefox 60 the icon in address bar would sometimes disappear. Not sure whether that is related to this issue.

**Comment by tanriol** [comment]
> I met the same situation today. The Brief option disappeared on my Firefox 60.0b16 (beta) on Windows 10; I tested on another machine with Firefox 59.0.2 (stable) on Windows 8.1 and it worked great. So I guess something on Firefox 60 breaks it?

As a wild guess, Firefox sometimes hides some of the extension buttons under a button called "More tools" or something like that. Are you sure it's not hiding there? Is it visible anywhere in customize mode?

> In addition, on Firefox 60 the icon in address bar would sometimes disappear. Not sure whether that is related to this issue.

Do you mean that on the same site it's visible in a different version, but not in 60? Again, can it be hiding in the "Page actions" menu?

**Comment by franklinyu** [comment]
> As a wild guess, Firefox sometimes hides some of the extension buttons under a button called "More tools" or something like that. Are you sure it's not hiding there? Is it visible anywhere in customize mode?

Never mind. I mean the icon in address bar, not the one in tool bar. I figured out that the icon only appears when there is a feed link in the HTML page.

> Do you mean that on the same site it's visible in a different version, but not in 60? Again, can it be hiding in the "Page actions" menu?

Yes. For example, when I visit <https://github.com/torvalds/linux/releases.atom> with Firefox 59, I can see "Brief" in "Subscribe to this feed using" drop down. When I visit that URL with Firefox 60, I cannot see "Brief" there.

I can still subscribe by clicking the icon in URL bar. The icon in address bar will appear when I visit <https://github.com/torvalds/linux/releases>, whether in Firefox 59 or 60. However for some feed there is no such HTML page.

**Comment by tanriol** [comment]
Thank you for an example link! Now I can at least partially reproduce the problem.

**Comment by tanriol** [comment]
Feed preview integration is broken since [this commit](https://hg.mozilla.org/integration/mozilla-inbound/rev/07ab807639ee). IIUC, this change means that the feed preview page is no longer available to content scripts (and possibly other manipulation by extensions). Brief could still detect the URL, but it has no reliable way to know this is a feed and not just some page. The commit references [bug 1436482](https://bugzilla.mozilla.org/show_bug.cgi?id=1436482), but it seems to be under a security embargo and I have no access to it.

**Comment by franklinyu** [comment]
I cannot access the bug page either.

Note that @n8v8R mentioned 59.0b13 which is a beta release. I guess Mozilla had this modification in Firefox 59 Beta, but decided to defer this change to 60, so Firefox 59 Stable did not come out with such issue.

**Comment by jnachtigall** [comment]
Just for the record, I've also reported this 'RSS add-on `brief` not suggested as 'Subscribe to this feed using' any more' issue to BMO (https://bugzilla.mozilla.org/show_bug.cgi?id=1460263) and I was told that:

> brief was relying on a security bug in the feed preview page to inject itself into the list. It doing something else instead is https://github.com/ancestorak/brief/issues/343

**Comment by n8v8R** [comment]
Seems that the referenced FF bug is likely to have serious security implications since Mozilla is guarding it so closely, perhaps to prevent to malicious intent.

Question is now whether Brief can be fixed, and when, or whether that is the end of the road and one has to start looking for an alternative rather soon.

**Comment by tanriol** [comment]
This is not the end and a fix will be released in the next version.

**Comment by n8v8R** [comment]
That is a relief to know, looking forward to it.

**Comment by jnachtigall** [comment]
@tanriol Still not working for me (Firefox Nightly Windows 10) using current add-on version. No "brief" available:
![image](https://user-images.githubusercontent.com/3307404/41234094-8b55d944-6d8b-11e8-8baf-570c5dfef8fb.png)

**Comment by tanriol** [comment]
@jnachtigall Correct, it's not in that list and, likely, will never be there. Extensions have no access to it since Firefox 60. Please use the Brief icon in the address bar (it's even animated to be more visible).

Special case: if you're using WebRender, the icon may be blank for some reason (reported as [mozilla bug 1464927](https://bugzilla.mozilla.org/show_bug.cgi?id=1464927)). Still, it's there and its tooltip is "Subscribe".

**Comment by jnachtigall** [comment]
I see, I was using https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/ (before that I used the default firefox browser action based icon) 

Since both do not work anymore, maybe adding some note that always the brief icon must be used would be nice.


Awesome RSS page action *icon* by the way looks a bit more inline with the Firefox Photon guides to be honest. This is brief (which was hidden behind the 3 dots):

![image](https://user-images.githubusercontent.com/3307404/41288019-224f605e-6e45-11e8-8682-e03e7c33463d.png)

Maybe some cooperation with Awesome RSS by @shgysk8zer0 would also be fruitful to avoid code.duplication. 

Awesome RSS also has a field for which application to use for subscribing:

![image](https://user-images.githubusercontent.com/3307404/41288194-c6f801d8-6e45-11e8-95b0-b55811b2d5f2.png)

So maybe @shgysk8zer0 might consider adding everyone's favorite RSS reader a.k.a. `brief` :)

**Comment by tanriol** [comment]
> Awesome RSS page action icon by the way looks a bit more inline with the Firefox Photon guides to be honest.

Yeah, but the Brief icon is more recognizable to Brief users. I'm quite bad at design and don't have time for a visual redesign at the moment.

Cooperation with Awesome RSS sounds interesting, but needs some time. Filed #372.
