### ISSUE TITLE
Add feesd via link

### ISSUE THREAD

**Issue by tuxmaster5000** [brief-rss/brief#408]
On some web pages the feeds are only present as hyper links. 
But I don't see an function to add this links.
For example the site http://wildfly.org/
here you can add the feed only by click on the link in the footer.
When I click on it, firefox will add it to it rss system itself and not to brief.
Environment:
CentOS 7.6
FF: 60.3.0esr (64-Bit)
Brief: 2.5.8

**Comment by tuomosipola** [comment]
The ability to add feeds with a link would be extremely useful. E.g. https://soundcloud.com/ has the RSS link but not in the metadata so Brief doesn't recognise the feed.

**Comment by tanriol** [comment]
There's no more RSS system in Firefox, but the idea is worth evaluating.

**Comment by popovn** [comment]
Возможно было бы удобней добавить возможность сканирования всех ссылок на странице - на предмет того ведут ли они на валидный rss и предоставлять список для выбора/добавления.

**Comment by tanriol** [comment]
Since [2.6.0a0](https://github.com/brief-rss/brief/releases/tag/v2.6.0a0) this works by opening the link, which opens the Brief feed preview tab with a Subscribe button on it.

@popovn A normal page nowadays has hundreds of links. I'm afraid fetching them all to check whether there are any feeds is usually not a good idea.
