### ISSUE TITLE
firefox will not exit cleanly

### ISSUE THREAD

**Issue by atomGit** [brief-rss/brief#417]
Brief v2.5.9
FF v64
Manjaro Linux 18

this is difficult to reproduce, but after Brief is installed and, apparently after it's been used for a while, it eventually causes the Firefox process to remain after exiting

solution is to disable Brief, exit and kill the FF process, restart FF and it will exit cleanly

**Comment by Klipper** [comment]
Brief v2.5.9
FF v65.0.1 (but issue already from v64)
Windows 10

Same problem over here. 
When I exit Firefox with Brief enabled, Firefox process remains, and I need to use the Windows  taskmanager to kill the process. Then when restarting Firefox with Brief still enabled, Brief stopped working: no manualy or automatic refresh possible enymore. 

Only solution to get Brief working again is to disable Brief. Close Firefox, kill the remaining Firefox process, after that restart Firefox and re-enable Brief.

**Comment by Sxderp** [comment]
Do the processes linger for more than a few minutes? I rarely close Firefox, actually I rarely shut down my computer. I don't tend to hit problems with shutdowns. However, I have noticed occasionally Firefox will take a minute or two before I can reopen (since it locks the profile and won't start unless terminated). But this usually passes shortly.

**Comment by tanriol** [comment]
I've never seen problems like this. Might be that Firefox was doing some kind of housekeeping. Closing the issue as stale, please reopen if it still reproduces.
