### ISSUE TITLE
What I've been missing for a long time. . . 

### ISSUE THREAD

**Issue by Freudentaumel** [brief-rss/brief#454]
I had already mentioned the subject some time ago, but did not get along with the solution proposed by Denis (tanriol). Maybe my suggestion can be implemented by the developer.

Updating the feeds takes - at least manually - extremely slow. In this slowness I don't know that from other feed readers. 

What are the reasons for this? Can't the developer speed up the update permanently?

**Comment by Ngamer01** [comment]
Feed update checking is how it is by default because:
1) The more feeds checked at once, the higher the probability of the update checks failing, locking up, or timing out.
2) It's a form of flood protection to keep Brief from being banned as a DoS/DDoS attack vector.  That's why the reader was set to only check one feed at a time per configured time period.

If you want to risk DoS/DDoS bans by configuring the update check period, these are the values to change in about:config --
1) extensions.brief.update.defaultFetchDelay : This is how long Brief takes to check each feed before moving to the next one.  Value is in milliseconds.  I have a value of 4000ms on mine (it's about 2/3rds of a minute).

2) extensions.brief.update.interval : This is how long until Brief starts a new cycle of checking feeds for updates.  Values are in seconds.  I have a value of 900 seconds on mine (that's 15 minutes).  You can configure this in Brief's options if you don't want to use the about:config way.

3) extensions.brief.update.startupDelay : When you boot up Firefox, this is how long Brief waits before it begins its first cycle of checking for feed updates before swapping to normal operations with the value for default fetch delay.  Values are in milliseconds.  I have a value of 180000ms on mine (that's 3 minutes).

There is no way to change Brief from checking one feed at a time to multiple feeds at one time.  All checks are done one-at-time regardless of your configured options/about:config.

**Comment by tanriol** [comment]
@Freudentaumel There are several purposes, including DDoS protection and lag reduction due to feed fetching / parsing. The latter is now much less important than it used to be, but DDoS protection is still a reason. I'm going to revise the specific values, however.

@Ngamer01 Not in `about:config` nowadays, these can be configured as Brief preferences with `Prefs.set(name, value)` in the Brief tab debug console (and without the `extensions.brief.` prefix).

**Comment by Freudentaumel** [comment]
>  I'm going to revise the specific values, however.

Thank you, Denis.
