### ISSUE TITLE
[Firefox 128] Clearing private data causes Brief to reask for permission to use persistent storage.

### ISSUE THREAD

**Issue by Ngamer01** [brief-rss/brief#549]
I'm on Firefox 128 on Windows 10.  When one clears their private data (or just cookies and site data) in the revamped "clear recent history" section, Firefox will delete Brief's permission to use persistent storage causing Brief to reask for permission.  This never happened prior to Firefox 128 as you could freely clear private data and Brief remembered its persistent storage permission every time pre-128.

If this is something not fixable on Brief's end, I am open to workarounds if anyone knows of any.  I'd just like to stop being asked to use persistent storage in Brief after clearing private data.

Firefox used to be set to "always allowed" for persistent storage on Brief, but 128 makes it default to "always ask" following private data clearing.  Here's an image of Brief's permissions on its custom webpage.

![image](https://github.com/user-attachments/assets/97f5b2bf-0502-43f5-af1c-9bf0c208b100)

**Comment by tanriol** [comment]
Hm, that's interesting... this was the case since at least Firefox 60, but then it was triggered by the "site settings" checkmark. The new clear history dialog has moved it to the "cookies and site data group" that's active by default and that users likely mean to use.

I've reported this issue as [mozilla bug 1907732](https://bugzilla.mozilla.org/show_bug.cgi?id=1907732).

**Comment by tanriol** [comment]
Looks like the storage actually stays persistent, so this could be worked around by checking `navigator.storage.persisted()` before calling `persist()`.
